FROM python:3.7-alpine
WORKDIR /usr/src/app
COPY . .
RUN apk update && apk upgrade && apk add --no-cache bash git openssh
RUN /usr/local/bin/python -m pip install --upgrade pip && pip install -r requirements.txt
CMD [ "pytest", "-v", "-s" ] 
